### ISSUE TITLE
TypeError: CoinGecko is not a constructor

### ISSUE THREAD

**Issue by AlexBarbulescu** [miscavage/CoinGecko-API#1]
Tested with the example given, what's wrong?
```
/var/www/Crypto/syncPriceData.js:14
const CoinGeckoClient = new CoinGecko();
                        ^

TypeError: CoinGecko is not a constructor
    at Object.<anonymous> (/var/www/Crypto/syncPriceData.js:14:25)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:303:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:872:3)
```

**Comment by miscavage** [comment]
Hi @AlexBarbulescu - Thank you for spotting.
This issue has been fixed with commit: 3229d61
Please update the module to the latest version.
Closing this issue.
