### ISSUE TITLE
Coins list fetching api call fails with parse error

### ISSUE THREAD

**Issue by omeryousaf** [miscavage/CoinGecko-API#17]
## Description
I am using this library to scrape data from coingecko platform but i have recently started receiving the following error a lot
```
SyntaxError: Unexpected token e in JSON at position 0
at JSON.parse (<anonymous>)
at IncomingMessage.<anonymous> (/home/omer/abc-miner/node_modules/coingecko-api/lib/CoinGecko.js:864:25)
at IncomingMessage.emit (events.js:327:22)
at endReadableNT (internal/streams/readable.js:1327:12)
at processTicksAndRejections (internal/process/task_queues.js:80:21)

```
on checking the source code at `node_modules/coingecko-api/lib/CoinGecko.js:864` i find this 
```
res.on('end', () => {
          try {
            body = Buffer.concat(body);
            body = body.toString();

            //Check if page is returned instead of JSON
            if (body.startsWith('<!DOCTYPE html>')) {
              Utils._WARN_('Invalid request', 'There was a problem with your request. The parameter(s) you gave are missing or incorrect.');
            } else if (body.startsWith('Throttled')) {
              Utils._WARN_('Throttled request', 'There was a problem with request limit.');
            }

            //Attempt to parse
>>            body = JSON.parse(body);    // this is the line referred to in the error stack i-e CoinGecko.js:864
          }
          catch (error) {
            reject(error);
          };
...
```

I use [this way of fetching a list coins list](https://github.com/miscavage/CoinGecko-API#coinslist), here is my code
```
try  {
  const CoinGecko = require('coingecko-api');
  const CoinGeckoClient = new CoinGecko();
  console.log('before calling CG api');
  let response = await CoinGeckoClient.coins.list();
  console.log('after calling CG api'); // this log rarely works
} catch(err) {
  console.log(err)
}
```

**Comment by eisa-rezaei** [comment]
I am getting 403 error for calling this api  `await CoinGeckoClient.coins.all()`

**Comment by james-katz** [comment]
I'm having the same issue here.
The weird thing is, on my machine it works ok. But when i run on my Lightsail instance I get this error.
Both my machine and my Lightsail uses node.js version 18.12.1

**Comment by riordant** [comment]
Same problem here, local is ok, on an AWS instance getting 403

**Comment by zakjanzi** [comment]
So, any luck with this? I can't get it to run. Exact issue as OP.

**Comment by sachiew** [comment]
hey, you might wanna try looking at the user agent, to resolve the 403 error.

**Comment by omeryousaf** [comment]
i think we ended up switching to calling the [coingecko platform API](https://www.coingecko.com/en/api/documentation) directly 
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/6904200/234471750-93ba30f4-37ba-4aa2-94ec-6a13d9d7e400.png">
