### ISSUE TITLE
Error message with CoinGeckoClient.coins.markets endpoint

### ISSUE THREAD

**Issue by BennieBe** [miscavage/CoinGecko-API#45]
I recently implemented the markets endpoint which was working fine until recently. There was a recent change in Coingecko API for the markets endpoint (I think), so now when I am calling the markets endpoint, it gives me this error message: 

```
SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/node_modules/coingecko-api/lib/CoinGecko.js:864:25)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:69766) UnhandledPromiseRejectionWarning: Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.header (/node_modules/express/lib/response.js:794:10)
    at ServerResponse.send (/node_modules/express/lib/response.js:174:12)
    at ServerResponse.json (/node_modules/express/lib/response.js:278:15)
    at /api.routes.js:167:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:69766) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:69766) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is what I am using in my call as parameters:
  ```
CoinGeckoClient.coins.markets({
            ids: coinNames,
            vs_currency: currencyUsed,
            localization: false
    }) 
     .then(data => {
       ...
    })
```

**Comment by DeclanMurphy** [comment]
I've been getting this for a few days as well. Coingecko reported a related issue on their status page. Even though the status page says it has since been resolved, I am still getting the error.

https://status.coingecko.com/

I've implemented an API call to coinmarketcap instead as a fallback.

**Comment by lost-in-trance** [comment]
I am still having this error

After some debugging i found out that If you have a blank user agent the api returns "error code: 1020"

With a user agent set, it works as it should

I did a temp fix by editing the _buildRequestOptions function to add the user agent

`  _buildRequestOptions(path, params) {
    //Stringify object params if exist
    if (Utils.isObject(params)) params = querystring.stringify(params);
    else params = undefined;

    //Make relative path
    //Check if has params, append accordingly
    if (params == undefined) path = `/api/v${Constants.API_VERSION}${path}`;
    else path = `/api/v${Constants.API_VERSION}${path}?${params}`;
   
    //Return options
    return {
      path,
      method: 'GET',
      host: Constants.HOST,
      port: 443,
      timeout: CoinGecko.TIMEOUT,
      headers: {
        'User-Agent': 'Node',
      }
    };
  };

`

**Comment by Escaflownevan** [comment]
Same for me since a few days

if calling:  await CoinGeckoClient.coins.markets ->
SyntaxError: Unexpected token e in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (18ada5b.js:2)
    at IncomingMessage.emit (node:events:406)
    at endReadableNT (node:internal/streams/readable:1343)
    at processTicksAndRejections (node:internal/process/task_queues:83)

**Comment by TiagoAndreAlmeida** [comment]
i still getting this erro today

**Comment by sachiew** [comment]
> i still getting this erro today

did you try to amend your user-agent? As suggested by @lost-in-trance

**Comment by BennieBe** [comment]
@TiagoAndreAlmeida I stopped using the markets endpoint from the library and just implemented it on my own directly with the CoinGecko API. That works without any issues. So that would be an alternative approach that you could take if you cannot get it to work with this library here

**Comment by TiagoAndreAlmeida** [comment]
Thanks @BennieBe i Will try out
